const GET_INSTANT_WEATHER_REQUEST = 'GET_INSTANT_WEATHER_REQUEST';
const GET_INSTANT_WEATHER_SUCCESS = 'GET_INSTANT_WEATHER_SUCCESS';
const GET_INSTANT_WEATHER_FAILED = 'GET_INSTANT_WEATHER_FAILED';

const GET_FORECAST_WEATHER_REQUEST = 'GET_FORECAST_WEATHER_REQUEST';
const GET_FORECAST_WEATHER_SUCCESS = 'GET_FORECAST_WEATHER_SUCCESS';
const GET_FORECAST_WEATHER_FAILED = 'GET_FORECAST_WEATHER_FAILED';

export {
  GET_INSTANT_WEATHER_REQUEST,
  GET_INSTANT_WEATHER_SUCCESS,
  GET_INSTANT_WEATHER_FAILED,
  GET_FORECAST_WEATHER_REQUEST,
  GET_FORECAST_WEATHER_SUCCESS,
  GET_FORECAST_WEATHER_FAILED,
};
